### ISSUE TITLE
请问同时支持全局样式和局部cssModules吗？

### ISSUE THREAD

**Issue by beijipc** [lnlfps/symph-joy#3]
- [ ] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |         |
| node    |         |
| OS      |         |
| browser |         |
| etc     |         |

**Comment by lnlfps** [comment]
支持的，在样式文件中使用以下语法
```css
:global {
  .global-class-name {
    color: green;
  }
}
```
参考css-module的使用文档 https://github.com/css-modules/css-modules#usage-with-preprocessors
